
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list custom_templates/

# configuration.yaml
lovelace:
  mode: storage
  dashboards:
    main-dashboard:        # must contain a hyphen
      mode: yaml
      title: Main
      show_in_sidebar: true
      icon: mdi:view-dashboard
      filename: dashboards/main.yaml
      require_admin: false   # optional
      
input_text:
  lg_toast_message:
    name: LG TV Toast
    icon: mdi:message-processing
    max: 120